### PR TITLE
Create Simple_calculator.py

### PR DESCRIPTION
**Pull request by eeshwarantharan**

### CODE REVIEW

**Comment by eeshwarantharan** [comment]
I have some more of my basic programs... 
(I am a beginner in coding in Python)
Can I PR in here?

**Comment by virusahi** [comment]
Ya offcourse

**Comment by eeshwarantharan** [comment]
Btw, u didn't assign hacktoberfest label to this commit
is that psble?

**Comment by virusahi** [comment]
Yes, I did.

**Comment by eeshwarantharan** [comment]
I will upload the remaining files tmrw, but u can add labels to the specific commit for It to be valid under hacktober fest.

**Pull request merged**
